controllers/UserController.php
<?php

namespace app\controllers;

use app\models\UserIdentity;
use app\models\UserLoginForm;
use app\models\UserJoinForm;
use yii;
use app\models\UserRecord;
use \yii\web\Controller;


class UserController extends Controller
{
    public function actionJoin()
    {
        if (Yii::$app->request->isPost)
        {
            return $this->actionJoinPost();
        }
        $userJoinForm = new UserJoinForm();
        $userRecord = new UserRecord();

        $userRecord->setTestUser();
        $userJoinForm->setUserRecord($userRecord);

        return $this->render('join', compact('userJoinForm'));
    }

    public function actionJoinPost()
    {
        $userJoinForm = new UserJoinForm();
        if ($userJoinForm->load(Yii::$app->request->post()))
        {
            if ($userJoinForm->validate())
            {
                $userRecord = new UserRecord();
                $userRecord->setUserJoinForm($userJoinForm);
                $userRecord->save();
                return $this->redirect('/user/login');
            }

        };

        return $this->render('join', compact('userJoinForm'));
    }

    public function actionLogin()
    {
        $userLoginForm = new UserLoginForm;
        if (Yii::$app->request->isPost)
        {
            return $this->actionLoginPost();
        }
        return $this->render('login', compact('userLoginForm'));
    }

    public function actionLoginPost()
    {
        $userLoginForm = new UserLoginForm();
        if ($userLoginForm->load(Yii::$app->request->post()))
            if ($userLoginForm->validate())
            {
                $userLoginForm->login();
                return $this->redirect('/');
            }
        return $this->render('login', compact('userLoginForm'));
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->redirect('/');
    }


}

views/layouts/main.php
<?php
use \yii\bootstrap\NavBar;
use \yii\bootstrap\Nav;

$this->beginPage(); ?>
<html>
<head>
<!--    <title>test yii2 site</title>-->
    <?php $this->head(); ?>
</head>

<body>
<?php $this->beginBody(); ?>
    <?php
        NavBar::begin([
            'brandLabel' => 'Amega',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => ['class' => 'navbar-default navbar-fixed-top']
                    ]);

        if (Yii::$app->user->isGuest)
        {
            $items = [
                ['label' => 'Join', 'url' => ['/user/join']],
                ['label' => 'Login', 'url' => ['/user/login']]
            ];
        }
        else
        {
            $items = [
                ['label' => Yii::$app->user->getIdentity()->name],
                ['label' => 'Logout', 'url' => ['/user/logout']]
            ];
        }

        echo Nav::widget([
           'options' => ['class' => 'navbar-nav navbar-rigth'],
           'items' => $items
        ]);

        NavBar::end();
    ?>

    <div class="container" style="margin-top: 50px"></div>
        <?= $content ?>
    </div>

    <?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>